**Python List**

In [3]:
#list elements are all same type
zoo = ['bear','lion','panda']
print(zoo)

['bear', 'lion', 'panda']


In [4]:
#list elements are not all same type
biggerzoo = ['bear',['panda']]
print(biggerzoo)

['bear', ['panda']]


Lists, strings, tuples are sequence types since they store ordered collection of items. Program can iterate over sequence types, which is why lists, strings, tuples, sets are "iterables".

**Agenda**:
* 1.When to use lists, tuples, dictionaries or sets?
* 2.Randomly select an element in a list
* 3.Transform lists into other data structures
* 4.append() vs extend()
* 5.sort() vs sorted()
* 6.Clone or copy a list
* 7.List comprehension
* 8.Count occurences of a list item
* 9.Split a list into evenly sized chunks
* 10.Loop over a list
* 11.Create flat lists out of lists
* 12.Get intersection of lists
* 13.Remove duplicates from lists
* 14.NumPy vs Lists
* 15.NumPy arrays
* 16.Math with lists

**1.When to use lists, tuples, dictionaries or sets?**

List vs Tuple<br/>
If you're defining a constant set of values and just need to iterate through it, use tuple. Tuple is faster and safer than list.

List vs Dictionaries<br/>
* List stores items with order, while dictionaries don't have order.
* Dictionaries are know to associate each key with a value, while lists just contain values.

Lists vs Sets<br/>
* Sets have no order, same as dictionaries.
* Sets require the items contained in it to be hashable, lists store non-hashable items.
* Sets require items to be unique and immutable. Lists allow duplicates and mutable.
* hashable: floats, integers, tuples, strings. Hashability makes an object usable as a dictionary key and a set member, because these data structures use the hash value internally.
* non-hashable: dictionaries, sets, lists

In [7]:
import collections
#check if a dictionary is hashable
print(isinstance({}, collections.Hashable))

False


In [8]:
#check if a float is hashable
print(isinstance(0.125, collections.Hashable))

True


**2.Randomly select an element in a list**

In [9]:
from random import choice

In [10]:
list = ['a','b','c']
print(choice(list))

c


In [11]:
from random import randrange
randomLetters = ['a','b','c']
#select a random index from lists
randomIndex = randrange(0,len(randomLetters))
print(randomLetters[randomIndex])

b


**3.Transform lists into other data structures**

convert a list to a string

In [4]:
listofstr = ['one','two','three']
tostr = ''.join(listofstr)
print(tostr)

listofnum = [1,2,3]
tostr = ''.join(str(n) for n in listofnum)
print(tostr)

onetwothree
123


convert a list to tuple

In [5]:
tuple(listofstr)

('one', 'two', 'three')

convert a list to set

In [6]:
set(listofstr)

{'one', 'three', 'two'}

convert lists to dictionaries

In [11]:
helloworld = ['hello','world','1','2']
#make sure key-value pairs
helloworld_dict = dict(zip(helloworld[0::2], helloworld[1::2]))
print(helloworld_dict)

{'hello': 'world', '1': '2'}


In [13]:
a = [1,2,3,4,5,6]
#create a list iterator object
i = iter(a)
#zip and create dictionary
print(dict(zip(i,i)))

{1: 2, 3: 4, 5: 6}


**4. append() vs extend()**

check whether a variable is iterable

In [15]:
shortList = [5,6,7,8]
shortList.__iter__

<method-wrapper '__iter__' of list object at 0x106333d08>

extend(): takes an iterable(list, set, tuple or string), adds each element of the iterable to the list one at a time

append(): adds its argument to the end of the list as a single item

In [16]:
shortList.append([4,5])
print(shortList)

[5, 6, 7, 8, [4, 5]]


In [17]:
longerList = [5,6,7,8]
longerList.extend([4,5])
print(longerList)

[5, 6, 7, 8, 4, 5]


extend() is a more efficient version of calling append() multiple times.

**5. sort vs sorted**

sorted() returns a new sorted list without affecting the original list. 
Also, it sorts any iterable, not just lists.

sort() sorts the list in-place, mutating the list indices and returns None.

**6. Clone or copy a list**

* Slice original list and store it into a new variable: newList = oldList[:]
* newList = list(oldList)
* newList = copy.copy(oldList)
* if list contains objects and you want to copy those, use copy.deepcopy(oldList)

In [20]:
import copy as c
groceries = ['apple', 'fish']
groce1 = c.copy(groceries)
groce2 = c.deepcopy(groceries)
print(groce2)

['apple', 'fish']


**7. List comprehension**

In [22]:
[x**2 for x in range(10) if x%2 == 0]

[0, 4, 16, 36, 64]

transform lists into other lists

In [25]:
mylist = [1,2,3,4,5]
[(lambda x: x*x)(x) for x in mylist]
#f = lambda x: x*x
#[f(x) for x in range(10)]

[1, 4, 9, 16, 25]

**8. Count occurences of a list item**

In [26]:
list1 = ["d", "a", "t", "a", "c", "a", "m", "p"]
list1.count("a")

3

counting all items in a list with count()

In [38]:
list1 = ["a","b","b"]
[[x,list1.count(x)] for x in set(list1)]

[['b', 2], ['a', 1]]

counting all items with counter()

In [39]:
from collections import Counter
list1 = ["a","b","b"]
Counter(list1)

Counter({'a': 1, 'b': 2})

**9. Split a list into evenly sized chunks**

In [83]:
# Your list `x`
x = [1,2,3,4,5,6,7,8]
z = zip(*[iter(x)]*3)
print(*z)

(1, 2, 3) (4, 5, 6)


In [88]:
def chunks(list, chunksize):
    for i in range(0, len(list), chunksize):
        yield list[i:i+chunksize]

print(*chunks(range(4),2))

range(0, 2) range(2, 4)


In [90]:
list = range(0,20)
chunk = 5
#split up list into chunks
[list[i:i+chunk] for i in range(0,len(list),chunk)]

[range(0, 5), range(5, 10), range(10, 15), range(15, 20)]

**10. Loop over a list**

In [47]:
mylist = [[1,2,3],[4,5,6,7],[8,9,10]]

for x in mylist:
    if len(x) == 3:
        print(x)

[1, 2, 3]
[8, 9, 10]


In [48]:
mylist = [3,4,5,6]

#print tuples of all indices and values
for i, val in enumerate(mylist):
    print(i,val)

0 3
1 4
2 5
3 6


In [51]:
mylist = [[1,2,3],[4,5,6,7],[8,9,10]]
[x for x in mylist if len(x)==3]

[[1, 2, 3], [8, 9, 10]]

**11. Create flat lists out of lists**

use sum() to flatten lists

In [52]:
list = [[1,2],[3,4],[5,6]]
sum(list,[])

[1, 2, 3, 4, 5, 6]

use reduce() 

In [53]:
listofLists = [[1,2],[3,4],[5,6]]
from functools import reduce
print(reduce(lambda x,y: x+y, listofLists))

[1, 2, 3, 4, 5, 6]


use for loop

In [61]:
print([item for sublist in listofLists for item in sublist])
#list1 = []
#for sublist in list:
#  for item in sublist:
#      list1.append(item)

[1, 2, 3, 4, 5, 6]


**12. Get intersection of two lists**

use filter()

In [108]:
list1 = [1, 6, 7, 10, 13, 28, 32, 41, 58, 63]
list2 = [[13, 17, 18, 21, 32], [7, 11, 13, 14, 28]]
intersection = [(filter(lambda x: x in list1, sublist)) for sublist in list2]
print(*intersection[0])
print(*intersection[1])

13 32
7 13 28


use sets

In [94]:
list1 = [1, 6, 7, 10, 13, 28, 32, 41, 58, 63]
list2 = [13, 17, 18, 21, 32, 7, 11, 13, 14, 28, 1, 5, 6, 8, 15, 16]
print(*(set(list1) & set(list2)))
print(*(set(list1).intersection(list2)))

32 1 6 7 13 28
32 1 6 7 13 28


**13. Remove duplicates from lists**

In [109]:
duplicates = [1, 2, 3, 1, 2, 5, 6, 7, 8]
print(*set(duplicates))

1 2 3 5 6 7 8


In [111]:
smallnum = [1,2,3]
print(*(set(duplicates) - set(smallnum)))

8 5 6 7


**14. NumPy vs Lists**

* NumPy arrays are more compact than lists
* Access in reading and writing items is faster with NumPy
* NumPy has vector and matrix operations free

**15. NumPy arrays**

In [112]:
import numpy
numpy.array([])

array([], dtype=float64)

In [113]:
numpy.zeros(shape=(4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [114]:
numpy.ones(3)

array([1., 1., 1.])

In [115]:
numpy.empty(shape=(0,0))

array([], shape=(0, 0), dtype=float64)

**16. Math with lists**

weighted average of a list

In [116]:
cost = [0.424, 0.4221, 0.4185, 0.4132, 0.413]
cases = [10, 20, 30, 40, 50]
for c in range(len(cost)):
    cost[c] = (cost[c]*cases[c]/sum(cases))
cost = sum(cost)
print(cost)

0.41609999999999997


In [118]:
cost = [0.424, 0.4221, 0.4185, 0.4132, 0.413]
cases = [10, 20, 30, 40, 50]
sum(cost[c]*cases[c]/sum(cases) for c in range(len(cost)))

0.41609999999999997

In [121]:
cost = [0.424, 0.4221, 0.4185, 0.4132, 0.413]
cases = [10, 20, 30, 40, 50]
print(*zip(cost,cases))
print(sum([x*y for x,y in zip(cost,cases)]) / sum(cases))

(0.424, 10) (0.4221, 20) (0.4185, 30) (0.4132, 40) (0.413, 50)
0.41609999999999997


quantile of a list

In [122]:
import numpy as np
a = np.array([1,2,3,4,5])
p = np.percentile(a,50)
print(p)

3.0


sum lists element-wise

In [124]:
list1 = [1,2,3]
list2 = [4,5,6]
from operator import add
print(*(map(add,list1,list2)))

5 7 9


In [136]:
res = [x+y for x,y in zip(list1,list2)]
print(res)

[5, 7, 9]


In [134]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
sum_v = v1 + v2
print(sum_v)

[5 7 9]


Reference: https://www.datacamp.com/community/tutorials/18-most-common-python-list-questions-learn-python#question3